name: Build Flipper App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          echo "== repo root =="
          pwd
          echo "== tree =="
          ls -la
          echo "== find application.fam (any depth) =="
          find . -type f -iname "application.fam" -print || true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi

      - name: Install ufbt
        run: |
          python -m pip install --upgrade pip
          pip install ufbt
          ufbt --version

      - name: Locate app directory (robust)
        id: findapp
        shell: bash
        run: |
          set -e
          # Try to find application.fam anywhere (case-insensitive)
          APP_DIR="$(find . -type f -iname 'application.fam' | head -n1 | sed 's|/[^/]*$||')"
          if [ -z "$APP_DIR" ]; then
            # Fallback: if ./erhu_tuner exists, use it
            if [ -d "./erhu_tuner" ]; then
              APP_DIR="./erhu_tuner"
            else
              echo "ERROR: Could not find application.fam and no ./erhu_tuner folder present."
              echo "Repo tree for debugging:"
              find . -maxdepth 3 -print
              exit 1
            fi
          fi
          echo "Using app dir: $APP_DIR"
          echo "appdir=$APP_DIR" >> $GITHUB_OUTPUT
          # Show its contents
          echo "== contents of app dir =="
          ls -la "$APP_DIR"

      - name: Build app
        shell: bash
        working-directory: ${{ steps.findapp.outputs.appdir }}
        run: |
          ufbt update || true
          ufbt build
          echo "Search for .fap after build:"
          find . ~/.ufbt -type f -name "*.fap" -print || true

      - name: Collect .fap artifacts
        shell: bash
        run: |
          set -e
          mkdir -p artifact_out
          find . ~/.ufbt -type f -name "*.fap" -print -exec cp -v {} artifact_out/ \; || true
          echo "Collected files:"
          ls -la artifact_out || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: erhu_tuner_build
          path: artifact_out/**
          if-no-files-found: error
